package model;

// Generated 29 janv. 2016 00:30:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", catalog = "cashretracted")
public class Compte implements java.io.Serializable {

	private Integer idcompte;
	private User user;
	private Long solde;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public Compte() {
	}

	public Compte(User user) {
		this.user = user;
	}

	public Compte(User user, Long solde, Set<Transaction> transactions) {
		this.user = user;
		this.solde = solde;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcompte", unique = true, nullable = false)
	public Integer getIdcompte() {
		return this.idcompte;
	}

	public void setIdcompte(Integer idcompte) {
		this.idcompte = idcompte;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_iduser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "solde", precision = 10, scale = 0)
	public Long getSolde() {
		return this.solde;
	}

	public void setSolde(Long solde) {
		this.solde = solde;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
