package model;

// Generated 29 janv. 2016 00:30:49 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "cashretracted")
public class Transaction implements java.io.Serializable {

	private Integer idtransaction;
	private Compte compte;
	private Integer montant;
	private String date;

	public Transaction() {
	}

	public Transaction(Compte compte) {
		this.compte = compte;
	}

	public Transaction(Compte compte, Integer montant, String date) {
		this.compte = compte;
		this.montant = montant;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idtransaction", unique = true, nullable = false)
	public Integer getIdtransaction() {
		return this.idtransaction;
	}

	public void setIdtransaction(Integer idtransaction) {
		this.idtransaction = idtransaction;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "compte_idcompte", nullable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "montant")
	public Integer getMontant() {
		return this.montant;
	}

	public void setMontant(Integer montant) {
		this.montant = montant;
	}

	@Column(name = "date", length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
